services:
  - type: web
    name: secther-chat-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: false
